#!/bin/bash

set -e

if [ ! -d venv/ ]; then
    virtualenv venv -p python3.7
    source venv/bin/activate
    pip install -r requirements.txt
else
    source venv/bin/activate
fi


mypy --ignore-missing-imports . || true
flake8 --exclude=venv . || true
pytest --color=yes -v "$*"